---
name: scheduled
on:
  workflow_dispatch: { }  # Allows manually trigger this workflow
  schedule:
    - cron: "0 3 * * *"

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  scheduled:
<<<<<<< HEAD
    uses: cloudposse/.github/.github/workflows/shared-terraform-scheduled.yml@main
    secrets: inherit
=======
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/scheduled.yml@main
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
>>>>>>> 5caa648 (Merge remote-tracking branch 'upstream/main' into feature/openidconnect-auth-0.92.0)
